import { DEMO_PHOTO, DEMO_SIGNATURE_IMAGE } from './base64Images';

export const DEMO_USER_DATA = {
  photoUrl: DEMO_PHOTO,
  firstName: 'John',
  lastName: 'Doe',
  company: 'Microsoft.',
  jobTitle: 'CEO',
  email: 'john@gmail.com',
  phone: '',
  isSocialIconsActive: '1',
  instagramLink: '',
  facebookLink: '',
  linkedinLink: '',
  xLink: '',
  youtubeLink: '',
  tiktokLink: '',
  githubLink: '',
  websiteLink: '',
  whatsappLink: '',
  instagramIconUrl: '',
  facebookIconUrl: '',
  linkedinIconUrl: '',
  xIconUrl: '',
  youtubeIconUrl: '',
  tiktokIconUrl: '',
  githubIconUrl: '',
  websiteIconUrl: '',
  whatsappIconUrl: '',
  signatureImageUrl: DEMO_SIGNATURE_IMAGE,
  badgeTemplate: ``,
  photoLink: '',
  nameFontSize: '15px',
  jobTitleFontSize: '12px',
  companyFontSize: '12px',
  emailFontSize: '12px',
  phoneFontSize: '12px',
  nameFontStyle: 'font-weight: bold;',
  jobTitleFontStyle: '',
  companyFontStyle: '',
  emailFontStyle: '',
  phoneFontStyle: '',
  photoBorderRadius: 'border-radius: 10px !important;',
  buttons: '',
  button1Text: 'enter text',
  button1Link: '',
  button2Text: 'enter text',
  button2Link: '',
  bannerUrl: '',
  bannerLink: '',
  photoSize: '80',
  companyLogoUrl: '',
  companyLogo: '',
  signatureAlignment: 'middle',
  signatureBackgroundColor: '#ffffff',
  signatureBorderRadius: '10px',
  signaturePadding: '5px',
};
